version: "3.9"

services:
  structurizr:
    image: structurizr/lite:latest
    container_name: structurizr
    ports:
      - "8080:8080"
    volumes:
      - "./c4model:/workspace"  # tu carpeta mapeada
    working_dir: /workspace/workSpaces/NimacOptiWork
    restart: unless-stopped
